port: 12000
mysql:
  "master":
    "host": "127.0.0.1"
    "port": 3306
    "username": "root"
    "password": "mysql123"
    "db_name": "dapp_dropbox"
  "max_open_conns": 40
  "max_idle_conns": 20
  "log_level": "info"
node_endpoint: "127.0.0.1:6000"
depot_bootstrap: [
  "enr:-Ky4QPjfQ5S5q-IJEI231L7Mv1ICP4JhWNmCRB7v9mBQFkiGMIZf4x7v4uWnDuzjhnv-s6jiYjkp3sMfrm3itQwIOCaGAYTgHSRYh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEDdaKn4Ryb2xlhG5vZGWJc2VjcDI1NmsxoQLxTElPoVGvS8CJAZQ-OOw14REjNI_CZ_gFWnVMKegqDIN0Y3CCGDiDdWRwghic"
]
